[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

opacity = 0.90
blur = true

option_as_alt = "Both"

[window.dimensions]
columns = 175
lines = 50

[font]
normal.family = "ComicShannsMonoNerdFont"

size = 14

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]
